---
title: "R graph GBS"
author: "mykyta"
date: "18/03/2022"
output: html_document
---
```{r}
library('dplyr')
library('ggplot2')
library('reshape2')
library('googleVis')
```

```{r}
sdse <- read.table(file = "porcellato_SDSE_data.csv", 
                   sep = ";", header=TRUE)
sdsd <- read.table(file = "porcellato_SDSD_data.csv", 
                   sep = ";", header=TRUE)
refseq <- read.table(file = "refseq_data.csv", 
                   sep = ";", header=TRUE)
ena661k <- read.table(file = "ena661k_data.csv", 
                     sep = ";", header=TRUE)
labstrains <- read.table(file = "labstrains_data.csv", 
                      sep = ";", header=TRUE)
```

```{r}
sdse <- sdse[!sdse$excluded == "yes",]
sdsd <- sdsd[!sdsd$excluded == "yes",]
ena661k <- ena661k[!ena661k$excluded == "yes",]
labstrains <- labstrains[!labstrains$excluded == "yes",]
refseq <- refseq[!refseq$excluded == "yes",]
```

```{r}
unique_values <- ena661k %>% group_by(ST) %>% summarize(count=n())
unique_values <- merge(unique_values, refseq %>% group_by(ST) %>% summarize(count=n()), all = TRUE,by = "ST")
unique_values <- merge(unique_values, labstrains %>% group_by(ST) %>% summarize(count=n()), all = TRUE,by = "ST")
unique_values <- merge(unique_values, sdse %>% group_by(ST) %>% summarize(count=n()), all = TRUE,by = "ST")
unique_values <- merge(unique_values, sdsd %>% group_by(ST) %>% summarize(count=n()), all = TRUE,by = "ST")

columns_names <- c("ST","ena661k","refseq","labstrains","Porcellato SDSE","Porcellato SDSD")

names(unique_values) = columns_names

m_unique_values <- melt(unique_values, id.vars = "ST")

m_unique_values <- m_unique_values[!m_unique_values$ST == "-",]

m_unique_values <- na.omit(m_unique_values)

m_unique_values_sum <- aggregate(m_unique_values$value,list(m_unique_values$ST), sum)

# m_unique_values_otherst <- m_unique_values_sum[m_unique_values_sum[,2] < 10,1]
# 
# m_unique_values_sum_dataset <- m_unique_values[m_unique_values$ST %in% m_unique_values_otherst,]
# 
# m_unique_values_sum_dataset <- aggregate(m_unique_values_sum_dataset$value,list(m_unique_values_sum_dataset$variable),sum)
# 
# m_unique_values_sum_dataset <- cbind(c("ena661k","refseq","labstrains","SDSE","SDSD"),m_unique_values_sum_dataset)
# 
# names(m_unique_values_sum_dataset) <- c('dataset','variable','value')

m_unique_values_sum <- m_unique_values_sum[m_unique_values_sum[,2] >= 10,]


m_unique_values_filtered <- m_unique_values[m_unique_values$ST %in% m_unique_values_sum$Group.1,]

totals<- m_unique_values_filtered %>%
  group_by(ST) %>%
  summarise(total=sum(value))

# stacked barplot
ggplot(data=m_unique_values_filtered, aes(x=value, y=ST, fill = variable)) +
  geom_bar(stat="identity") +  scale_fill_viridis_d() + ggtitle('Most Common ST') +
  theme(plot.title = element_text(hjust = 0.5)) +  geom_text(data = totals ,aes(x=total,y=ST,label=total,fill=NULL),nudge_x= 5, size = 3)
```

```{r}
unique_values <- ena661k %>% group_by(serotype) %>% summarize(count=n())
unique_values <- merge(unique_values, refseq %>% group_by(serotype) %>% summarize(count=n()), all = TRUE,by = "serotype")
unique_values <- merge(unique_values, labstrains %>% group_by(serotype) %>% summarize(count=n()), all = TRUE,by = "serotype")
unique_values <- merge(unique_values, sdse %>% group_by(serotype) %>% summarize(count=n()), all = TRUE,by = "serotype")
unique_values <- merge(unique_values, sdsd %>% group_by(serotype) %>% summarize(count=n()), all = TRUE,by = "serotype")

columns_names <- c("serotype","ena661k","refseq","labstrains","Porcellato SDSE","Porcellato SDSD")

names(unique_values) = columns_names

m_unique_values <- melt(unique_values, id.vars = "serotype")

m_unique_values <- m_unique_values[!m_unique_values$serotype == "-",]

m_unique_values <- na.omit(m_unique_values)

m_unique_values_sum <- aggregate(m_unique_values$value,list(m_unique_values$serotype), sum)

m_unique_values_sum <- aggregate(m_unique_values$value,list(m_unique_values$serotype), sum)

m_unique_values_sum <- m_unique_values_sum[m_unique_values_sum[,2] >= 20,]

m_unique_values_filtered <- m_unique_values[m_unique_values$serotype %in% m_unique_values_sum$Group.1,]

totals<- m_unique_values_filtered %>%
  group_by(serotype) %>%
  summarise(total=sum(value))

#Change color of SDSE TO green as in other graphic
ggplot(data=m_unique_values_filtered, aes(x= value, y=serotype, fill = variable)) + labs(y = "M types") +
  geom_bar(stat="identity") +  scale_fill_manual(values = c("#440154FF","#3B528BFF","#21908CFF","#5DC863FF")) + ggtitle('Most Common M-types') +
  theme(plot.title = element_text(hjust = 0.5)) + geom_text(data = totals ,aes(x=total,y=serotype,label=total,fill=NULL),nudge_x= 5, size = 3)
# geom_text(aes(label = m_unique_values_filtered$value), size = 3, position = position_stack(vjust = 0.5), color = "white") add labels to separate bars
```
```{r}
Count_dataset <- data.frame(Dataset = c("ena661k","Refseq","Labstrains","Porcellato SDSE","Porcellato SDSD"), 
                            Size = c(nrow(ena661k),nrow(refseq),nrow(labstrains),nrow(sdse),nrow(sdsd)))
```

```{r}
#googlevis

Pie <- gvisPieChart(Count_dataset,options = list(colors="['#440154','#3B528B','#21908C','#5DC863','#FDE725']",height="900",width="900", is3D = TRUE, pieSliceText = 'value', pieSliceTextStyle = "{fontSize:13}" ))

plot(Pie, browser = rstudioapi::viewer)
```


```{r}

Count_dataset[,1] <- c("1","2","3","4","5")

Count_dataset <- Count_dataset %>% 
  arrange(desc(Dataset)) %>%
  mutate(ypos = cumsum(Size)- 0.5*Size )


ggplot(Count_dataset, aes(x="", y=Size, fill=Dataset)) +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0) + scale_fill_manual(values = c("#440154FF","#3B528BFF","#21908CFF","#5DC863FF","#FDE725FF"), 
                                                labels =   c("ena661k","Refseq","Labstrains","Porcellato SDSE","Porcellato SDSD")) + 
  theme_void() + geom_text(aes(y = ypos, label = Size), color = "Black", size=3) + ggtitle('Total number of assemblies') +
  theme(plot.title = element_text(hjust = 0.5))
```

